#!/bin/bash
set -x
nb="csw-dev-0"
direction=${1:-put}

dest=~/cswsync/${nb}

[[ ! -d $dest ]] && {
    ! mkdir -p $dest && {
	echo "ERROR: could not create local sync dir $dest"
	exit -1
    }
}	

case $direction in
    get|from|pull)
	oc rsync ${nb}: $dest
	;;
    put|push|to)
	oc rsync ${dest}/ ${nb}:
	;;
esac

