#!/bin/bash

nb=${1:-csw-dev}
ns=${2:-''}
[[ -n $ns ]] && ns="-n $ns"

oc patch notebook $nb $ns --type merge -p '{"metadata":{"annotations":{"kubeflow-resource-stopped":"'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"}}}'
